# Game Integrator API Production Configuration

server:
  port: "8080"
  host: "0.0.0.0"

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  name: "gameintegrator"
  ssl: "disable"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: "1h"

jwt:
  secret: "dev-secret-key"
  expiry: "24h"

wallet:
  url: "http://wallet:8000"
  api_key: "secret-key"

log:
  level: "info" 