# Game Integrator API Production Configuration

server:
  port: "8080"
  host: "0.0.0.0"

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "${DB_PASSWORD}"
  name: "game_integrator"
  ssl: "require"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: "1h"

jwt:
  secret: "${JWT_SECRET}"
  expiry: "24h"

wallet:
  url: "http://wallet-service:8000"
  api_key: "${WALLET_TOKEN}"

log:
  level: "info" 