# Game Integrator API Development Configuration

server:
  port: "8080"
  host: "localhost"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "game_integrator_dev"
  ssl: "disable"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: "1h"

jwt:
  secret: "dev-secret-key"
  expiry: "24h"

wallet:
  url: "http://localhost:8000"
  api_key: "token"

log:
  level: "debug" 